#!/bin/bash
today=`date +%Y%m%d`
echo $today
cur_dir=$(dirname $0)
cd $cur_dir
file_path=`pwd`
cd $cur_dir/../..
home=`pwd`
# echo $home
export PYTHONPATH=$home
source /etc/profile

echo "python3 ${file_path}/$@"
python3 $file_path/$@
